CREATE DATABASE IF NOT EXISTS vulscan CHARACTER SET utf8;

USE vulscan;

CREATE TABLE IF NOT EXISTS login
(
  uid VARCHAR(64) PRIMARY KEY,
  username VARCHAR(32) UNIQUE NOT NULL,
  password VARCHAR(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS task
(
  tid INT PRIMARY KEY,
  uid VARCHAR(64) NOT NULL,
  domain VARCHAR(256),
  ip_addr VARCHAR(256),
  ctime VARCHAR(32) NOT NULL,
  type VARCHAR(16) NOT NULL
);

CREATE TABLE IF NOT EXISTS result
(
  tid INT PRIMARY KEY,
  pid INT NOT NULL,
  type VARCHAR(16) NOT NULL,
  result VARCHAR(10240) DEFAULT NULL
)